### ISSUE TITLE
destroy方法报错了

### ISSUE THREAD

**Issue by AndrewXiGua** [wechat-miniprogram/lottie-miniprogram#1]
VM3457:1 thirdScriptError
Cannot set property 'innerHTML' of undefined; [Component] Event Handler Error @ index/index#bound clear
TypeError: Cannot set property 'innerHTML' of undefined
    at CanvasRenderer.destroy (http://127.0.0.1:25634/appservice/lottie-miniprogram.js:3615:83)
    at AnimationItem.destroy (http://127.0.0.1:25634/appservice/lottie-miniprogram.js:4932:63)
    at ye.clear (http://127.0.0.1:25634/appservice/index/index.js:83:14)
    at Object.r.safeCallback (WAService.js:1:1125173)
    at WAService.js:1:1317978
    at r (WAService.js:1:1249680)
    at WAService.js:1:1249802
    at WAService.js:1:420977
    at n (http://127.0.0.1:25634/appservice/__dev__/asdebug.js:1:27894)
    at e.exports.<anonymous> (http://127.0.0.1:25634/appservice/__dev__/asdebug.js:1:28236)

**Comment by AndrewXiGua** [comment]
![1567426989196](https://user-images.githubusercontent.com/20917295/64114430-84161c80-cdbf-11e9-93d6-e5f489f091f0.jpg)

**Comment by AndrewXiGua** [comment]
这个地方加一个判断```this.animationItem.wrapper=this.animationItem.wrapper || {}```如何

**Comment by seasonhuang** [comment]
这个是 lottie-web 的问题，已经给他们提 [issue](https://github.com/airbnb/lottie-web/issues/1772) 了。如果要用到，就先稍微改下 lottie-web 的源码。
